openapi: 3.0.0
info:
  title: ACME Air Flights Service
  description: Provides flight information for ACME Air and allows users to create/manage flight bookings.
  version: 1.0.0

servers:
  - url: http://localhost:8080/v1
    description: Local development server

paths:
  /flights:
    post:
      summary: Get flights for the requested travel parameters.
      description: Retrieves available flights based on the provided origin city code, destination city code, and travel date.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                origin:
                  type: string
                  description: Origin city airport code
                  enum: ["AKL", "WLG", "CHC", "DUD", "ZQN", "HLZ", "NSN", "NPE", "TRG", "IVC", "NPL", "PMR"]
                  example: "AKL"
                destination:
                  type: string
                  description: Destination city airport code
                  enum: ["AKL", "WLG", "CHC", "DUD", "ZQN", "HLZ", "NSN", "NPE", "TRG", "IVC", "NPL", "PMR"]
                  example: "WLG"
                date:
                  type: string
                  format: date
                  description: Travel date in DD/MM/YYYY format
                  example: "25/07/2025"
            example:
              origin: "AKL"
              destination: "WLG"
              date: "25/07/2025"
      responses:
        '200':
          description: Successfully retrieved list of flights.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    flightId:
                      type: string
                      format: uuid
                      example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                    flightCode:
                      type: string
                      example: "ACME217"
                    origin:
                      type: string
                      example: "AKL"
                    destination:
                      type: string
                      example: "WLG"
                    departureTime:
                      type: string
                      format: date-time
                      example: "2025-08-15T08:30:00Z"
                    arrivalTime:
                      type: string
                      format: date-time
                      example: "2025-08-15T09:35:00Z"
                    price:
                      type: number
                      format: double
                      example: 89.99
                example:
                  - flightId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                    flightCode: "ACME217"
                    origin: "AKL"
                    destination: "WLG"
                    departureTime: "2026-07-25T08:30:00Z"
                    arrivalTime: "2026-07-25T09:35:00Z"
                    price: 89.99
                  - flightId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                    flightCode: "ACME168"
                    origin: "AKL"
                    destination: "WLG"
                    departureTime: "2026-07-25T14:00:00Z"
                    arrivalTime: "2026-07-25T15:05:00Z"
                    price: 120.00
        '400':
          description: Bad request (can include multiple error messsages).
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
              example:
                errors:
                  - message: "Request body is invalid or missing."
                  - message: "Origin city code is invalid or missing."
                  - message: "Destination city code is invalid or missing."
                  - message: "Travel date must be provided in DD/MM/YYYY format."
        '422':
          description: Semantically valid request but validation issues.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
              example:
                errors:
                  - message: "Origin and destination city cannot be the same."
                  - message: "Travel date cannot be in the past."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
              example:
                errors:
                  - message: "Internal server error."